version: 2.1
jobs:
  Ensure parser up-to-date:
    docker:
      - image: circleci/rust:latest
    resource_class: small
    steps:
      - checkout
      - run: ./parser-gen/ensure_parser_up_to_date.sh
orbs:
  rust: glotrade/rust@0.1.3
workflows:
  build:
    jobs:
      - rust/check
      - rust/format
      - rust/test
      - Ensure parser up-to-date
